"use client";

import { useAppSelector } from "@/store/hooks";
import { Sparkles, MessageSquare, ArrowRight, HelpCircle } from "lucide-react";
import { motion } from "framer-motion";

const EASE = [0.22, 1, 0.36, 1] as const;

export default function ExplanationTab() {
  const { activeResults } = useAppSelector((s) => s.dataset);

  if (
    !activeResults ||
    !activeResults.explanation_results ||
    activeResults.explanation_results.length === 0
  ) {
    return (
      <div className="space-y-8 pb-12">
        <motion.div
          initial={{ opacity: 0, y: 6 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, ease: EASE }}
        >
          <h1 className="text-3xl font-semibold text-[#1D1D1F] tracking-tight">
            Explanation
          </h1>
          <p className="text-sm text-[#6E6E73] mt-1.5">
            Plain-language findings for your dataset, column by column.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 6 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, ease: EASE, delay: 0.05 }}
          className="rounded-[28px] border border-white/50 bg-white/90 backdrop-blur-xl shadow-[0_8px_30px_rgba(0,0,0,0.06)] px-10 py-16 text-center"
        >
          <div className="w-12 h-12 rounded-2xl bg-[#F5F5F7] flex items-center justify-center mx-auto mb-4">
            <HelpCircle className="w-5 h-5 text-[#AEAEB2]" strokeWidth={1.5} />
          </div>
          <p className="text-sm text-[#6E6E73]">
            An explanation hasn&apos;t been generated yet.
          </p>
        </motion.div>
      </div>
    );
  }

  const explanation = activeResults.explanation_results[0];
  const columns = explanation.columns_json || [];

  return (
    <div className="space-y-8 pb-12">
      {/* 1. Page heading + generation source badge */}
      <motion.header
        initial={{ opacity: 0, y: 6 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, ease: EASE }}
        className="flex flex-col sm:flex-row sm:items-center gap-2.5 sm:gap-3.5"
      >
        <h1 className="text-3xl font-semibold text-[#1D1D1F] tracking-tight">
          Explanation
        </h1>
        {explanation.generated_by === "gemini" ? (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-[#0071E3]/10 px-3 py-1 text-xs font-medium text-[#0071E3] self-start sm:self-auto">
            <Sparkles className="w-3.5 h-3.5 shrink-0" />
            Generated by AI
          </span>
        ) : (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-[#F5F5F7] px-3 py-1 text-xs font-medium text-[#6E6E73] self-start sm:self-auto">
            <MessageSquare className="w-3.5 h-3.5 shrink-0" />
            Generated automatically
          </span>
        )}
      </motion.header>

      {/* 2. Overall summary -- lead paragraph, no card wrapper, so it reads
          like a headline finding rather than another tile in a grid. */}
      <motion.p
        initial={{ opacity: 0, y: 6 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, ease: EASE, delay: 0.05 }}
        className="text-lg sm:text-xl text-[#1D1D1F] leading-relaxed font-medium tracking-tight max-w-3xl"
      >
        {explanation.overall_summary}
      </motion.p>

      {/* 3. Per-column explanation cards */}
      <div className="space-y-4">
        {columns.map((col, idx) => (
          <motion.div
            key={idx}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, ease: EASE, delay: Math.min(0.1 + idx * 0.04, 0.4) }}
            className="rounded-[28px] border border-white/50 bg-white/90 backdrop-blur-xl shadow-[0_4px_12px_rgba(0,0,0,0.04)] px-6 py-6 space-y-5"
          >
            {/* Card header: column name */}
            <div className="pb-1">
              <h2 className="font-mono font-medium text-base text-[#1D1D1F] bg-[#F5F5F7] px-3 py-1.5 rounded-full inline-block">
                {col.target_column}
              </h2>
            </div>

            {/* Block 1: Summary */}
            <div className="space-y-1.5">
              <p className="text-xs font-medium text-[#AEAEB2] uppercase tracking-wider">
                Summary
              </p>
              <p className="text-sm text-[#3A3A3C] leading-relaxed">
                {col.plain_language_summary}
              </p>
            </div>

            {/* Block 2: What this means */}
            <div className="space-y-1.5">
              <p className="text-xs font-medium text-[#AEAEB2] uppercase tracking-wider">
                What this means
              </p>
              <p className="text-sm text-[#3A3A3C] leading-relaxed">
                {col.what_this_means_for_the_data}
              </p>
            </div>

            {/* Block 3: How it was handled */}
            <div className="space-y-1.5">
              <p className="text-xs font-medium text-[#AEAEB2] uppercase tracking-wider">
                How it was handled
              </p>
              <p className="text-sm text-[#3A3A3C] leading-relaxed">
                {col.imputation_explanation}
              </p>
            </div>

            {/* Block 4: Confidence -- set apart in a soft tinted container so
                it reads as an assessment, not just another paragraph. */}
            <div className="space-y-1.5">
              <p className="text-xs font-medium text-[#AEAEB2] uppercase tracking-wider">
                Confidence
              </p>
              <p className="text-sm font-medium text-[#1D1D1F] leading-relaxed bg-[#F5F5F7]/70 rounded-2xl px-4 py-3">
                {col.confidence_note}
              </p>
            </div>

            {/* Block 5: Recommended next step -- the one actionable item on
                the card, given the accent treatment. */}
            <div className="pt-1">
              <p className="text-xs font-medium text-[#AEAEB2] uppercase tracking-wider mb-1.5">
                Recommended next step
              </p>
              <div className="flex items-start gap-2.5 rounded-2xl bg-[#0071E3]/8 px-4 py-3.5">
                <ArrowRight className="w-4 h-4 text-[#0071E3] shrink-0 mt-0.5" />
                <span className="text-sm font-medium text-[#0A3D74] leading-relaxed">
                  {col.recommended_action}
                </span>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}